### ISSUE TITLE
missing dependencies -  follow the read me instructions not working

### ISSUE THREAD

**Issue by ntedgi** [sjoshi6/go-rest-api-boilerplate#2]
using
Docker version 18.03.1-ce, build 9ee9f40
macbook 10.13.5 high siera
go version go1.10.3 darwin/amd64

after running all installation and run go install

`main.go:8:2: cannot find package "github.com/markbates/going/defaults" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/markbates/going/defaults (from $GOROOT)
	/Users/naortedgi/go/src/github.com/markbates/going/defaults (from $GOPATH)
main.go:9:2: cannot find package "github.com/sjoshi6/go-rest-api-boilerplate/app" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/sjoshi6/go-rest-api-boilerplate/app (from $GOROOT)
	/Users/naortedgi/go/src/github.com/sjoshi6/go-rest-api-boilerplate/app (from $GOPATH)
main.go:10:2: cannot find package "github.com/sjoshi6/go-rest-api-boilerplate/logger" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/sjoshi6/go-rest-api-boilerplate/logger (from $GOROOT)
	/Users/naortedgi/go/src/github.com/sjoshi6/go-rest-api-boilerplate/logger (from $GOPATH)`

and https://github.com/markbates/going/defaults
leads to 404

**Comment by sjoshi6** [comment]
Could you try now ? I updated the glide dependencies to latest. It is working for me.
